#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));
require __DIR__.'/laravel_boot.php';

$app = app();
$app->singleton(
    Illuminate\Contracts\Foundation\Application::class,
    demo\Application::class
);

$app->singleton(
    Illuminate\Contracts\Console\Kernel::class,
    demo\Console\Kernel::class
);

$app->registers([
    demo\Console\Providers\ConsoleSupportServiceProvider::class,
]);

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

exit($status);
